apiVersion: v1
kind: Service
metadata:
  name: latam
  labels:
    app: latam
spec:
  type: LoadBalancer
  ports:
  - port: {{.Values.port}}
  selector:
    app: latam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latam-gke
  labels:
    app: latam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: latam
  template:
    metadata:
      labels:
        app: latam
    spec:
      containers:
      - name: latam
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.port}}
