apiVersion: apps/v1
kind: Deployment
metadata:
  name: Latam_Airlines_GKE
  labels:
    app: Latam
spec:
  selector:
    matchLabels:
      app: Latam
  template:
    metadata:
      labels:
        app: Latam
    spec:
      containers:
      - image: {{.Values.image}}
        name: Latam
        ports:
        - containerPort: {{.Values.port}}
