apiVersion: apps/v1
kind: Deployment
metadata:
  name: latam-airlines-gke
  labels:
    app: latam
spec:
  selector:
    matchLabels:
      app: latam
  template:
    metadata:
      labels:
        app: latam
    spec:
      containers:
      - image: {{.Values.image}}
        name: latam
        ports:
        - containerPort: {{.Values.port}}
        readinessProbe:
          tcpSocket:
            port: {{.Values.port}}
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{.Values.port}}
          initialDelaySeconds: 120
          periodSeconds: 20
