apiVersion: v1
kind: Service
metadata:
  name: latam
  labels:
    app: latam
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: latam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latam-gke
  labels:
    app: latam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latam
  template:
    metadata:
      labels:
        app: latam
    spec:
      containers:
      - name: latam
        image: nginx:1.14.2
        ports:
        - containerPort: 80
