apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacifico-app
  labels:
    app: pacifico
spec:
  selector:
    matchLabels:
      app: pacifico
  template:
    metadata:
      labels:
        app: pacifico
    spec:
      containers:
      - image: {{.Values.image}}
        name: pacifico
        ports:
        - containerPort: 8080